### ISSUE TITLE
Gelbbrustara malen, als Projektlogo

### ISSUE THREAD

**Issue by zolabar** [zolabar/trendPy#3]
Eigenen Gelbbrustrara als Logo fürs Projekt malen.

Auf Papier und fotografieren oder gleich digital.

**Comment by adavidho** [comment]
![LOGO_TrendPy](https://user-images.githubusercontent.com/105221763/176682115-d8037a54-6c43-4e49-8003-e33425dfacfd.jpg)

**Comment by zolabar** [comment]
@adavidho , cool! Danke

**Comment by zolabar** [comment]
@adavidho, ich werde das Projekt im August auf Zenodo hochladen. Wenn Sie als Co-Author aufgelistet werden wollen, dann bitte bis Mitte August als Autor in die [citation.cff](https://github.com/zolabar/trendPy/blob/main/citation.cff) Datei eintragen (synchronisieren mit der letzten version von main, citation.cff anpassen und pull-request machen)
