### ISSUE TITLE
problems with trigReg function in methods.py

### ISSUE THREAD

**Issue by Marcus02W** [zolabar/trendPy#6]
When testing the different regression approaches from methods.py in my local version of the TrendPy Webapp linear and polynomial worked fine. However the output of the trigReg function seems not to work correctly. Coefficients and trendline when using trigReg can be seen in the screenshot below.

![trigReg_coefficients](https://user-images.githubusercontent.com/105054212/176185746-cfbee161-b3bb-4f65-9335-5ec37d61a370.PNG)

**Comment by zolabar** [comment]
@Marcus02W , thank you for the feedback.

Can you attach that data?

 I suspect, that the ansatz needs to be shifted by the mean of the data (y-values). I will have a look at it

**Comment by zolabar** [comment]
@Marcus02W , you can test trig reg with the periodic data I just uploaded to the data folder

**Comment by Marcus02W** [comment]
@zolabar, I have tested trigReg with the periodic data and it's working fine :) expected the function to plot a periodic graph that is quite far off for the datapoints in the screenshot, but makes sense that it doesn't do that, so thanks for the explanation
